"""Generate run_bot_loop.yaml with enough chained legs to cover the rest of the season.

GitHub caps a single JOB at 6 hours but a workflow RUN at 35 days. Chaining legs with `needs`
therefore converts the job cap into the run cap, and one dispatch covers weeks instead of hours.
That matters because GitHub delivers no scheduled events for this account at all - a workflow that
did nothing but exist on a */5 cron missed six consecutive ticks - so `schedule` is not available
and every hour of coverage has to come from a dispatch.

The YAML is generated rather than hand-written because 150 near-identical job blocks is exactly
the kind of thing that rots when edited by hand. Edit this file and re-run it; do not edit the
generated workflow.

    python generate_loop_workflow.py           # regenerate with the defaults below
    python generate_loop_workflow.py --legs 40 # a shorter chain
"""

from __future__ import annotations

import argparse
from pathlib import Path

OUT = Path(__file__).parent / ".github" / "workflows" / "run_bot_loop.yaml"

# 5.5 rather than 6: GitHub kills the job at 6 hours, and a leg that is killed rather than
# finishing cleanly takes its `needs` successors down with it unless they guard on it.
HOURS_PER_LEG = 5.5

# 150 legs x 5.5h is about 34 days, just inside the 35-day cap on a workflow run, and covers
# 26 July to roughly 29 August against a season that closes on 6 September.
DEFAULT_LEGS = 150

HEADER = '''name: Forecast in a loop (scheduler-independent)

# GENERATED BY generate_loop_workflow.py - DO NOT EDIT BY HAND.
#
# GitHub delivers no scheduled events for this account. That is measured, not assumed: a workflow
# containing nothing but a */5 cron and an echo missed six consecutive ticks while Actions
# reported operational and the workflow read `active`. It is not the fork restriction either - the
# same thing happened after migrating to a non-fork repo. So `schedule` is unavailable and all
# coverage comes from dispatches.
#
# Coverage is the whole game. Tournament questions open and close inside a MEDIAN OF 2.4 HOURS, an
# unforecast question scores exactly zero, and prize share goes as the SQUARE of summed peer score.
#
# A job is capped at 6 hours; a workflow RUN is capped at 35 days. Chaining {legs} legs with `needs`
# converts one cap into the other: a single dispatch buys about {days:.0f} days of continuous
# forecasting, which covers the rest of the season with one press.
#
#     gh workflow run run_bot_loop.yaml -R LiamLacey95/pixelloop-forecasting-bot
#
# Each leg keeps going past a failing pass, and each leg runs even if the one before it failed, so
# a single bad question or provider blip costs one pass rather than the remaining weeks. Idle
# passes are nearly free: the bot skips questions it has already forecast, so a pass with nothing
# newly open costs one Metaculus API call and no LLM calls.
#
# Not scheduled itself, which would reintroduce the thing it works around. The concurrency group
# stops two dispatches overlapping and double-spending the budget.
on:
  workflow_dispatch:
    inputs:
      interval_minutes:
        description: "Minutes to wait between forecasting passes"
        required: false
        default: "20"

concurrency:
  group: forecast-loop
  cancel-in-progress: false

jobs:
'''

LEG = '''  leg{n}:
{needs}    uses: ./.github/workflows/forecast-leg.yaml
    with:
      hours: "{hours}"
      interval_minutes: ${{{{ inputs.interval_minutes }}}}
      leg: {n}
    secrets: inherit
'''


def build(legs: int) -> str:
    days = legs * HOURS_PER_LEG / 24
    parts = [HEADER.format(legs=legs, days=days)]
    for n in range(1, legs + 1):
        # `!cancelled()` rather than `success()`: a leg that fails or is killed at the 6-hour wall
        # must not end the chain, or one bad leg costs every remaining week of coverage.
        needs = "" if n == 1 else f"    needs: leg{n - 1}\n    if: ${{{{ !cancelled() }}}}\n"
        parts.append(LEG.format(n=n, needs=needs, hours=HOURS_PER_LEG))
    return "".join(parts)


if __name__ == "__main__":
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--legs", type=int, default=DEFAULT_LEGS)
    args = ap.parse_args()

    text = build(args.legs)
    OUT.write_text(text, encoding="utf-8")
    hours = args.legs * HOURS_PER_LEG
    print(f"wrote {OUT} - {args.legs} legs, {hours:.0f}h, {hours / 24:.1f} days of coverage")
    assert f"leg{args.legs}:" in text, "last leg missing"
    assert text.count("uses: ./.github/workflows/forecast-leg.yaml") == args.legs
    print("checks passed")
